/** Все тексты интерфейса — на русском, как в макетах. */
export const S = {
  appName: 'anyview',
  tagline: 'Аниме, сериалы и фильмы',
  nav: { home: 'Главная', anime: 'Аниме', series: 'Сериалы', movies: 'Фильмы', sections: 'Разделы', soonBadge: 'скоро' },
  logoLabel: 'anyview — на главную',
  search: {
    placeholder: 'Найти аниме…',
    placeholderFull: 'Название на русском или оригинальное',
    label: 'Поиск по названию',
    clear: 'Очистить',
    back: 'Назад',
    close: 'Закрыть поиск',
  },
  soon: {
    badge: 'В РАЗРАБОТКЕ',
    series: {
      title: 'Сериалы уже в пути',
      body: 'Собираем каталог сериалов с русскими и оригинальными названиями, рейтингами и списками серий по сезонам. А пока загляните в аниме: там уже всё работает.',
      features: ['Сезоны и серии в одном плейлисте', 'Рейтинги и описания', 'Выбор озвучки и качества'],
    },
    movies: {
      title: 'Фильмы уже в пути',
      body: 'Собираем каталог фильмов с русскими и оригинальными названиями, рейтингами и описаниями. А пока загляните в аниме: там уже всё работает.',
      features: ['Новинки и подборки', 'Рейтинги и описания', 'Выбор озвучки и качества'],
    },
    watchAnime: 'Смотреть аниме',
    toHome: 'На главную',
  },
  notFound: { title: 'Такой страницы нет', body: 'Возможно, ссылка устарела или в ней опечатка.', toAnime: 'Перейти в аниме' },
  common: { retry: 'Повторить', loadFailed: 'Не удалось загрузить', loadingMore: 'Загружаем ещё…', somethingWrong: 'Что-то пошло не так', tryLater: 'Проверьте соединение и попробуйте ещё раз' },
  card: { episode: (n: number) => `${n} серия`, rating: 'Рейтинг' },
  rail: { prev: 'Назад', next: 'Вперёд' },
  home: {
    fresh: 'Новые серии',
    freshAll: 'Все новые серии',
    all: 'Все',
    latest: 'Последние тайтлы',
    latestAll: 'Все тайтлы',
    catalog: 'Весь каталог',
    more: 'Показать ещё',
    soonTitle: 'Сериалы и фильмы скоро',
    soonTitleShort: 'Сериалы и фильмы',
    soonBody: 'Собираем каталог с рейтингами, описаниями и выбором озвучки',
    soonBodyShort: 'Скоро здесь — собираем каталог',
    more2: 'Подробнее',
  },
  title: {
    about: 'О тайтле',
    description: 'Описание',
    readMore: 'Читать полностью',
    collapse: 'Свернуть',
    tags: 'Теги',
    breadcrumbs: 'Хлебные крошки',
    watch: 'Смотреть',
    watchEpisode: (n: number) => `Смотреть ${n} серию`,
    continueEpisode: (n: number) => `Продолжить ${n} серию`,
    favorite: 'В избранное',
    unfavorite: 'Убрать из избранного',
    votes: (n: string, w: string) => `${n} ${w}`,
    poster: (name: string) => `Постер: ${name}`,
    infoType: 'Тип', infoEpisodes: 'Эпизоды', infoYear: 'Год', infoStatus: 'Статус', infoDirector: 'Режиссёр', infoVoice: 'Озвучка',
    episodes: 'Серии',
    released: (a: number, b: string) => `вышло ${a} из ${b}`,
  },
  player: {
    play: 'Воспроизвести', pause: 'Пауза', next: 'Следующая серия', prev: 'Предыдущая серия', quality: 'Качество видео',
    mute: 'Выключить звук', unmute: 'Включить звук', volume: 'Громкость', pip: 'Картинка в картинке',
    fullscreen: 'Во весь экран', exitFullscreen: 'Выйти из полноэкранного режима', seek: 'Перемотка',
    resume: (t: string) => `Продолжаем с ${t}`, fromStart: 'С начала',
    nextIn: (n: number) => `Следующая серия через ${n}…`, cancel: 'Отмена',
    failed: 'Не удалось загрузить видео',
    watched: 'Просмотрено', left: (m: number) => `Осталось ${m} мин`, isNew: 'Новая', playing: 'Играет',
    soon: 'Скоро', airs: (d: string) => `Выйдет ${d}`,
  },
  searchPage: {
    title: 'Поиск',
    scope: 'Где искать',
    anime: 'Аниме',
    seriesSoon: 'Сериалы · скоро',
    moviesSoon: 'Фильмы · скоро',
    recent: 'Недавние запросы',
    recentInline: 'Недавние:',
    popular: 'Часто ищут',
    heading: (q: string) => `Результаты по запросу «${q}»`,
    found: (n: number) => `Найдено: ${n >= 50 ? '50+' : n}`,
    emptyTitle: 'Ничего не нашли',
    emptyHint: 'Попробуйте оригинальное название или часть слова',
    prompt: 'Введите название',
  },
  footer: { left: 'anyview · MVP', right: 'Данные и видео: AnimeVost' },
  catalog: { title: 'Аниме', subtitle: (total: string, titles: string) => `Последние обновления · ${total} ${titles}` },
} as const;
